# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "linux-build"
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            make_cmd: "cmake"
          - os: macos-latest
            make_cmd: "cmake"
          - os: windows-latest
            make_cmd: "cmake.exe"

    steps:
    # Install Qt5
    - name: Install-Qt5
      uses: jurplel/install-qt-action@v2
      with:
        target: desktop
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build using CMake
      run: ${{ matrix.make_cmd }} -DCMAKE_BUILD_TYPE=Release -B "build_${{ matrix.os }}" . && ${{ matrix.make_cmd }} --build "build_${{ matrix.os }}"

    - name: Upload-binary
      uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: "build_${{ matrix.os }}"
