# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "linux-build"
  linux-build:
    runs-on: ubuntu-latest

    steps:
    # Install Qt5
    - name: Install-Qt5
      uses: jurplel/install-qt-action@v2
      with:
        target: desktop
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build using CMake
      run: cmake -B linux_build . && make -C linux_build -j$(nproc)

    - name: Upload-binary
      uses: actions/upload-artifact@v1
      with:
        name: linux-build
        path: linux_build/qt_test
